var keyData = {
	'a': {sound:new Howl({src: ['sounds/bubbles.mp3']}), colour: 'red'},
	'b': {sound:new Howl({src: ['sounds/clay.mp3']}), colour: 'green'},
	'c': {sound:new Howl({src: ['sounds/confetti.mp3']}), colour: 'red'},
	'd': {sound:new Howl({src: ['sounds/corona.mp3']}), colour: 'red'},
	'e': {sound:new Howl({src: ['sounds/dotted-spiral.mp3']}), colour: 'red'},
	'f': {sound:new Howl({src: ['sounds/piston-1.mp3']}), colour: 'red'},
	'g': {sound:new Howl({src: ['sounds/glimmer.mp3']}), colour: 'red'},
	'h': {sound:new Howl({src: ['sounds/moon.mp3']}), colour: 'red'},
	'i': {sound:new Howl({src: ['sounds/pinwheel.mp3']}), colour: 'red'},
	'j': {sound:new Howl({src: ['sounds/piston-2.mp3']}), colour: 'red'},
	'k': {sound:new Howl({src: ['sounds/piston-3.mp3']}), colour: 'red'},
	'l': {sound:new Howl({src: ['sounds/prism-1.mp3']}), colour: 'red'},
	'm': {sound:new Howl({src: ['sounds/prism-2.mp3']}), colour: 'red'},
	'n': {sound:new Howl({src: ['sounds/prism-3.mp3']}), colour: 'red'},
	'o': {sound:new Howl({src: ['sounds/splits.mp3']}), colour: 'red'},
	'p': {sound:new Howl({src: ['sounds/squiggle.mp3']}), colour: 'red'},
	'q': {sound:new Howl({src: ['sounds/strike.mp3']}), colour: 'red'},
	'r': {sound:new Howl({src: ['sounds/flash-1.mp3']}), colour: 'red'},
	's': {sound:new Howl({src: ['sounds/flash-2.mp3']}), colour: 'red'},
	't': {sound:new Howl({src: ['sounds/flash-3.mp3']}), colour: 'red'},
	'u': {sound:new Howl({src: ['sounds/timer.mp3']}), colour: 'red'},
	'v': {sound:new Howl({src: ['sounds/ufo.mp3']}), colour: 'red'},
	'w': {sound:new Howl({src: ['sounds/veil.mp3']}), colour: 'red'},
	'x': {sound:new Howl({src: ['sounds/wipe.mp3']}), colour: 'red'},
	'y': {sound:new Howl({src: ['sounds/.mp3']}), colour: 'red'},
	'z': {sound: new Howl({src: ['sounds/zig-zag.mp3']}), colour: 'red'},
};