var keyData = {
	'a': {sound:new Howl({src: ['sounds/bubbles.mp3']}), colour: '#7776BC'},
	'b': {sound:new Howl({src: ['sounds/clay.mp3']}), colour: '#CDC7E5'},
	'c': {sound:new Howl({src: ['sounds/confetti.mp3']}), colour: '#FFFBDB'},
	'd': {sound:new Howl({src: ['sounds/corona.mp3']}), colour: '#FFEC51'},
	'e': {sound:new Howl({src: ['sounds/dotted-spiral.mp3']}), colour: '#FF674D'},
	'f': {sound:new Howl({src: ['sounds/piston-1.mp3']}), colour: '#D3B88C'},
	'g': {sound:new Howl({src: ['sounds/glimmer.mp3']}), colour: '#230903'},
	'h': {sound:new Howl({src: ['sounds/moon.mp3']}), colour: '#23C9FF'},
	'i': {sound:new Howl({src: ['sounds/pinwheel.mp3']}), colour: '#E86252'},
	'j': {sound:new Howl({src: ['sounds/piston-2.mp3']}), colour: '#E87EA1'},
	'k': {sound:new Howl({src: ['sounds/piston-3.mp3']}), colour: '#EBB3A9'},
	'l': {sound:new Howl({src: ['sounds/prism-1.mp3']}), colour: '#69B578'},
	'm': {sound:new Howl({src: ['sounds/prism-2.mp3']}), colour: '#69B578'},
	'n': {sound:new Howl({src: ['sounds/prism-3.mp3']}), colour: '#3A7D44'},
	'o': {sound:new Howl({src: ['sounds/splits.mp3']}), colour: '#254D32'},
	'p': {sound:new Howl({src: ['sounds/squiggle.mp3']}), colour: '#181D27'},
	'q': {sound:new Howl({src: ['sounds/strike.mp3']}), colour: '#EF8275'},
	'r': {sound:new Howl({src: ['sounds/flash-1.mp3']}), colour: '#C3BF6D'},
	's': {sound:new Howl({src: ['sounds/flash-2.mp3']}), colour: '#0496FF'},
	't': {sound:new Howl({src: ['sounds/flash-3.mp3']}), colour: '#F4ACB7'},
	'u': {sound:new Howl({src: ['sounds/timer.mp3']}), colour: '#82AEB1'},
	'v': {sound:new Howl({src: ['sounds/ufo.mp3']}), colour: '#648DE5'},
	'w': {sound:new Howl({src: ['sounds/veil.mp3']}), colour: '#304C89'},
	'x': {sound:new Howl({src: ['sounds/wipe.mp3']}), colour: '#FFBC42'},
	'y': {sound:new Howl({src: ['sounds/.mp3']}), colour: '#D81159'},
	'z': {sound: new Howl({src: ['sounds/zig-zag.mp3']}), colour: '#8F2D56'},
};